name: Build and deploy Node.js app to Azure Web App - LTCHProjectcs436

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # ตรวจสอบว่า scripts "build" มีใน package.json

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4 # ใช้ version ล่าสุดของ upload-artifact
        with:
          name: node-app
          path: . # หรือระบุโฟลเดอร์หรือไฟล์ที่ต้องการ เช่น build/ หรือ release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4 # ใช้ version ล่าสุดของ download-artifact
        with:
          name: node-app

      - name: Debug - List files
        run: ls -la # คำสั่งนี้ช่วยตรวจสอบว่าไฟล์ถูกดาวน์โหลดมาถูกต้องหรือไม่

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6F4EE75A026E41119AAC3D128EA2B5A2 }} # ใช้ชื่อ Secrets ที่เหมาะสม
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_32FD17E3DAF3410FB93B3DD0DEE2A88E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_86CCCBE9E6A94B75A0624917C66AB444 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'LTCHProjectcs436'
          package: . # หรือเปลี่ยนเป็นชื่อไฟล์/โฟลเดอร์ที่เหมาะสม เช่น release.zip
